# Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
# If they are then placed in numerical order, with any repeats removed,
# we get the following sequence of 15 distinct terms:
# 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
# 0.6s
# O(n^2), probably room for improvement

import time
start_time = time.time()

terms = []
for a in range(2, 101):
    for b in range(2, 101):
        if a**b not in terms:
            terms.append(a**b)

print(len(terms))
print(time.time() - start_time)
